export const CATEGORIES = {
  joburi: {
    slug: 'joburi',
    name: 'Joburi',
    icon: '💼',
    subcategories: {
      it: { slug: 'it', name: 'IT & Software' },
      marketing: { slug: 'marketing', name: 'Marketing/PR' },
      vanzari: { slug: 'vanzari', name: 'Vânzări' },
      contabilitate: { slug: 'contabilitate', name: 'Finanțe/Contabilitate' },
      juridic: { slug: 'juridic', name: 'Juridic' },
      hr: { slug: 'hr', name: 'HR/Resurse Umane' },
      inginerie: { slug: 'inginerie', name: 'Inginerie/Tehnic' },
      constructii: { slug: 'constructii', name: 'Construcții' },
      transport: { slug: 'transport', name: 'Transport/Logistică' },
      horeca: { slug: 'horeca', name: 'HoReCa' },
      medical: { slug: 'medical', name: 'Sănătate/Farmacie' },
      educatie: { slug: 'educatie', name: 'Educație' },
      administrativ: { slug: 'administrativ', name: 'Administrativ/Secretariat' },
      muncitori: { slug: 'muncitori', name: 'Muncitori Calificați' },
      necalificati: { slug: 'necalificati', name: 'Necalificați' },
      'alte-joburi': { slug: 'alte-joburi', name: 'Altele' },
    },
  },
  imobiliare: {
    slug: 'imobiliare',
    name: 'Imobiliare',
    icon: '🏠',
    subcategories: {
      apartamente: { slug: 'apartamente', name: 'Apartamente' },
      case: { slug: 'case', name: 'Case & Vile' },
      terenuri: { slug: 'terenuri', name: 'Terenuri' },
      'spatii-comerciale': { slug: 'spatii-comerciale', name: 'Spații Comerciale' },
      birouri: { slug: 'birouri', name: 'Birouri' },
      garaje: { slug: 'garaje', name: 'Garaje & Parcări' },
      cazare: { slug: 'cazare', name: 'Cazare/Turism' },
    },
  },
  auto: {
    slug: 'auto',
    name: 'Auto',
    icon: '🚗',
    subcategories: {
      autoturisme: { slug: 'autoturisme', name: 'Autoturisme' },
      autoutilitare: { slug: 'autoutilitare', name: 'Autoutilitare' },
      camioane: { slug: 'camioane', name: 'Camioane' },
      microbuze: { slug: 'microbuze', name: 'Microbuze/Autobuze' },
      rulote: { slug: 'rulote', name: 'Rulote/Autorulote' },
      motociclete: { slug: 'motociclete', name: 'Moto/Scutere/ATV' },
      remorci: { slug: 'remorci', name: 'Remorci' },
      piese: { slug: 'piese', name: 'Piese & Accesorii Auto' },
      agricole: { slug: 'agricole', name: 'Utilaje Agricole' },
      constructii: { slug: 'constructii', name: 'Utilaje Construcții' },
      barci: { slug: 'barci', name: 'Bărci/Ambarcațiuni' },
    },
  },
  servicii: {
    slug: 'servicii',
    name: 'Servicii',
    icon: '🔧',
    subcategories: {
      reparatii: { slug: 'reparatii', name: 'Construcții & Renovări' },
      curatenie: { slug: 'curatenie', name: 'Curățenie' },
      'transport-serviciu': { slug: 'transport-serviciu', name: 'Transport & Mutări' },
      'it-serviciu': { slug: 'it-serviciu', name: 'IT & Tehnic' },
      'auto-service': { slug: 'auto-service', name: 'Auto Service' },
      frumusete: { slug: 'frumusete', name: 'Frumusețe & Wellness' },
      evenimente: { slug: 'evenimente', name: 'Evenimente' },
      meditatii: { slug: 'meditatii', name: 'Educație & Meditații' },
      'juridic-financiar': { slug: 'juridic-financiar', name: 'Juridic & Financiar' },
      sanatate: { slug: 'sanatate', name: 'Sănătate' },
      gradinarit: { slug: 'gradinarit', name: 'Grădină & Exterior' },
      'animale-servicii': { slug: 'animale-servicii', name: 'Animale de companie' },
      'foto-video': { slug: 'foto-video', name: 'Foto/Video' },
      'alte-servicii': { slug: 'alte-servicii', name: 'Altele' },
    },
  },
  electronice: {
    slug: 'electronice',
    name: 'Electronice',
    icon: '📱',
    subcategories: {
      telefoane: { slug: 'telefoane', name: 'Telefoane Mobile' },
      laptopuri: { slug: 'laptopuri', name: 'Laptopuri' },
      tablete: { slug: 'tablete', name: 'Tablete' },
      desktop: { slug: 'desktop', name: 'Desktop PC' },
      'tv-audio': { slug: 'tv-audio', name: 'TV & Audio' },
      gaming: { slug: 'gaming', name: 'Console Gaming' },
      'foto-video': { slug: 'foto-video', name: 'Camere Foto/Video' },
      'accesorii-electronice': { slug: 'accesorii-electronice', name: 'Accesorii' },
      'componente-pc': { slug: 'componente-pc', name: 'Componente PC' },
      'alte-electronice': { slug: 'alte-electronice', name: 'Alte Electronice' },
    },
  },
  moda: {
    slug: 'moda',
    name: 'Modă',
    icon: '👗',
    subcategories: {
      'haine-femei': { slug: 'haine-femei', name: 'Îmbrăcăminte Femei' },
      'haine-barbati': { slug: 'haine-barbati', name: 'Îmbrăcăminte Bărbați' },
      'haine-copii': { slug: 'haine-copii', name: 'Îmbrăcăminte Copii' },
      'incaltaminte-femei': { slug: 'incaltaminte-femei', name: 'Încălțăminte Femei' },
      'incaltaminte-barbati': { slug: 'incaltaminte-barbati', name: 'Încălțăminte Bărbați' },
      'incaltaminte-copii': { slug: 'incaltaminte-copii', name: 'Încălțăminte Copii' },
      'genti-accesorii': { slug: 'genti-accesorii', name: 'Genți & Accesorii' },
      bijuterii: { slug: 'bijuterii', name: 'Bijuterii & Ceasuri' },
      ochelari: { slug: 'ochelari', name: 'Ochelari' },
      lenjerie: { slug: 'lenjerie', name: 'Lenjerie & Costum Baie' },
    },
  },
  'casa-gradina': {
    slug: 'casa-gradina',
    name: 'Casă & Grădină',
    icon: '🏡',
    subcategories: {
      mobila: { slug: 'mobila', name: 'Mobilă' },
      electrocasnice: { slug: 'electrocasnice', name: 'Electrocasnice' },
      decoratiuni: { slug: 'decoratiuni', name: 'Decorațiuni' },
      iluminat: { slug: 'iluminat', name: 'Iluminat' },
      gradina: { slug: 'gradina', name: 'Grădină & Exterior' },
      unelte: { slug: 'unelte', name: 'Bricolaj & Unelte' },
      textile: { slug: 'textile', name: 'Textile Casă' },
      bucatarie: { slug: 'bucatarie', name: 'Bucătărie' },
      baie: { slug: 'baie', name: 'Baie' },
      'alte-casa': { slug: 'alte-casa', name: 'Altele' },
    },
  },
  sport: {
    slug: 'sport',
    name: 'Sport',
    icon: '⚽',
    subcategories: {
      fitness: { slug: 'fitness', name: 'Fitness & Sală' },
      biciclete: { slug: 'biciclete', name: 'Biciclete' },
      'sporturi-apa': { slug: 'sporturi-apa', name: 'Sporturi de Apă' },
      'sporturi-iarna': { slug: 'sporturi-iarna', name: 'Sporturi de Iarnă' },
      'sporturi-echipa': { slug: 'sporturi-echipa', name: 'Fotbal & Sporturi de Echipă' },
      tenis: { slug: 'tenis', name: 'Tenis & Sporturi cu Racheta' },
      running: { slug: 'running', name: 'Running & Atletism' },
      'arte-martiale': { slug: 'arte-martiale', name: 'Arte Marțiale' },
      outdoor: { slug: 'outdoor', name: 'Outdoor & Camping' },
      extreme: { slug: 'extreme', name: 'Sporturi Extreme' },
      'echipament-sport': { slug: 'echipament-sport', name: 'Echipament Sportiv General' },
    },
  },
  animale: {
    slug: 'animale',
    name: 'Animale',
    icon: '🐾',
    subcategories: {
      caini: { slug: 'caini', name: 'Câini' },
      pisici: { slug: 'pisici', name: 'Pisici' },
      pesti: { slug: 'pesti', name: 'Pești & Acvaristică' },
      pasari: { slug: 'pasari', name: 'Păsări' },
      rozatoare: { slug: 'rozatoare', name: 'Rozătoare' },
      reptile: { slug: 'reptile', name: 'Reptile & Amfibieni' },
      'accesorii-animale': { slug: 'accesorii-animale', name: 'Accesorii Animale' },
      hrana: { slug: 'hrana', name: 'Hrană & Îngrijire' },
      'alte-animale': { slug: 'alte-animale', name: 'Alte animale' },
    },
  },
  'mama-copilul': {
    slug: 'mama-copilul',
    name: 'Mama & Copilul',
    icon: '👶',
    subcategories: {
      carucioare: { slug: 'carucioare', name: 'Cărucioare & Scaune Auto' },
      'scaune-auto': { slug: 'scaune-auto', name: 'Scaune Auto Copii' },
      'mobilier-copii': { slug: 'mobilier-copii', name: 'Mobilier Copii' },
      'haine-bebe': { slug: 'haine-bebe', name: 'Haine Copii' },
      jucarii: { slug: 'jucarii', name: 'Jucării & Jocuri' },
      alaptare: { slug: 'alaptare', name: 'Alăptare & Hrănire' },
      siguranta: { slug: 'siguranta', name: 'Siguranță Copii' },
      ingrijire: { slug: 'ingrijire', name: 'Îngrijire Bebeluși' },
      'carti-educative': { slug: 'carti-educative', name: 'Cărți & Educație' },
      'alte-mama-copilul': { slug: 'alte-mama-copilul', name: 'Altele' },
    },
  },
} as const

export type CategoryKey = keyof typeof CATEGORIES
export type Category = (typeof CATEGORIES)[CategoryKey]

export function getCategoryBySlug(slug: string): Category | undefined {
  return Object.values(CATEGORIES).find((cat) => cat.slug === slug)
}

export function getAllCategories() {
  return Object.values(CATEGORIES).map((cat) => ({
    slug: cat.slug,
    name: cat.name,
    icon: cat.icon,
  }))
}

export function getCategoryIdBySlug(slug: string): number {
  const categoryMap: Record<string, number> = {
    joburi: 1,
    imobiliare: 2,
    auto: 3,
    servicii: 4,
    electronice: 5,
    moda: 6,
    'casa-gradina': 7,
    sport: 8,
    animale: 9,
    'mama-copilul': 10,
  }
  return categoryMap[slug] || 1
}
