export const ROMANIAN_CITIES = [
  'Alba Iulia',
  'Alexandria',
  'Arad',
  'Bacău',
  'Baia Mare',
  'Bistrița',
  'Botoșani',
  'Brăila',
  'Brașov',
  'București',
  'Buzău',
  'Călărași',
  'Cluj-Napoca',
  'Constanța',
  'Craiova',
  'Deva',
  'Drobeta-Turnu Severin',
  'Focșani',
  'Galați',
  'Giurgiu',
  'Iași',
  'Miercurea Ciuc',
  'Oradea',
  'Piatra Neamț',
  'Pitești',
  'Ploiești',
  'Râmnicu Vâlcea',
  'Reșița',
  'Satu Mare',
  'Sfântu Gheorghe',
  'Sibiu',
  'Slatina',
  'Slobozia',
  'Suceava',
  'Târgoviște',
  'Târgu Jiu',
  'Târgu Mureș',
  'Timișoara',
  'Tulcea',
  'Vaslui',
  'Zalău',
  // Orașe mai mici
  'Aiud',
  'Băicești',
  'Băltești',
  'Băneasa',
  'Bărlad',
  'Bârlad',
  'Bumbești',
  'Calarasi',
  'Câmpia Turzii',
  'Campulung',
  'Căprioară',
  'Carpineni',
  'Ceahlau',
  'Celaru',
  'Cernăvoda',
  'Cernavodă',
  'Chitila',
  'Cisnădie',
  'Codlea',
  'Comănești',
  'Constanța',
  'Corbu',
  'Corugea',
  'Cosești',
  'Covasna',
  'Cristur',
  'Curvă',
  'Darabani',
  'Dani',
  'Dăbuleni',
  'Deed',
  'Defileul Jiului',
  'Deleni',
  'Demiseni',
  'Derna',
  'Dragalina',
  'Dragonești',
  'Dragoslavele',
  'Drăchești',
  'Drăculești',
  'Drăgănești-Olt',
  'Drăgășani',
  'Drăgnești',
  'Drești',
  'Drieștari',
  'Driesți',
  'Dudeștii Noi',
  'Dudeștii Vechi',
  'Dudești',
  'Dudeștui',
  'Dulosini',
  'Dumești',
  'Dumitreștii de Jos',
  'Dumitreștii de Sus',
  'Dumitru-Vodă',
  'Dunareni',
  'Dunăreni',
] as const

export type City = (typeof ROMANIAN_CITIES)[number]
